### ISSUE TITLE
CMake Error

### ISSUE THREAD

**Issue by mrhen2324** [alliedvision/gst-vmbsrc#1]
Hello,

I copied CMakeUserPresets.json TAMPLATE and added the path to /home/User/Desktop/VimbaX_2023-1/api/lib/cmake/vmb under preset linux64. The command “cmake --preset linux64” is then executed. Unfortunately the following error occurs here:

-- The C compiler identification is GNU 9.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'gstreamer-1.0'
--   Found gstreamer-1.0, version 1.16.3
-- Checking for module 'gstreamer-base-1.0'
--   Found gstreamer-base-1.0, version 1.16.3
-- Found GSTREAMER_BASE_LIBRARY: /usr/lib/aarch64-linux-gnu/libgstbase-1.0.so
-- Found GSTREAMER_BASE_INCLUDE_DIR: /usr/include/gstreamer-1.0
-- Checking for module 'gstreamer-video-1.0'
--   Found gstreamer-video-1.0, version 1.16.3
-- Found GSTREAMER_VIDEO_LIBRARY: /usr/lib/aarch64-linux-gnu/libgstvideo-1.0.so
-- Found GSTREAMER_VIDEO_INCLUDE_DIR: /usr/include/gstreamer-1.0
-- Found GStreamer: /usr/lib/aarch64-linux-gnu/libgstreamer-1.0.so  
-- Checking for module 'glib-2.0'
--   Found glib-2.0, version 2.64.6
-- Found GLIB2: /usr/lib/aarch64-linux-gnu/libglib-2.0.so  
-- Checking for module 'gobject-2.0'
--   Found gobject-2.0, version 2.64.6
-- Found GObject: /usr/include/glib-2.0  
CMake Error at CMakeLists.txt:41 (find_package):
  By not providing "FindVmb.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Vmb", but
  CMake did not find one.

  Could not find a package configuration file provided by "Vmb" with any of
  the following names:

    VmbConfig.cmake
    vmb-config.cmake

  Add the installation prefix of "Vmb" to CMAKE_PREFIX_PATH or set "Vmb_DIR"
  to a directory containing one of the above files.  If "Vmb" provides a
  separate development package or SDK, be sure it has been installed.

-- Configuring incomplete, errors occurred!

Shouldn't the vmb-config.cmake file be found? Am I doing something wrong or is something missing?

**Comment by NiklasKroeger-AlliedVision** [comment]
The steps you are describing sound right for a Linux system.
- Copy `CMakeUserPresets.json.TEMPLATE` and name the copy `CMakeUserPresets.json`
- in `CMakeUserPresets.json` modify the linux64 preset value of the `Vmb_DIR` entry to the directory that contains `vmb-config.cmake`
- execute `cmake --preset linux64`

This should provide CMake with all the information needed to locate your Vimba X installation. I do not know, why the message you get indicates that it could not find `vmb-config.cmake`.

Could you double check the following things please:
- Make sure that on your system `/home/User/Desktop/VimbaX_2023-1/api/lib/cmake/vmb` (path you mentioned at the top of your issue report) contains the file `vmb-config.cmake`
- Make sure that you entered that path in the `linux64` preset and for the `Vmb_DIR` cache variable
    - If you want you can just copy and past the entire content of your `CMakeUserPresets.json` file here.
- What kind of Linux system are you using? Distribution and version would be helpful.
- What CMaker version are you using? `cmake --version` should give you a version string.

**Comment by mrhen2324** [comment]
Thanks for the fast respond. I checked the points.

- the path /home/User/Desktop/VimbaX_2023-1/api/lib/cmake/vmb contains the file vmb-config.cmake
- here is my CMakeUserPresets.json file

########################################

{
  "version": 3,
  "cmakeMinimumRequired": {
    "major": 3,
    "minor": 21,
    "patch": 0
  },
  "configurePresets": [
    {
      "name": "win64",
      "inherits": "win64-template",
      "cacheVariables": {
        "GSTREAMER_ROOT": {
          "type": "PATH",
          "value": "PATH_TO_GSTREAMER_INSTALLATION"
        },
        "Vmb_DIR": {
          "type": "PATH",
          "value": "PATH_TO_VimbaX/api/lib/cmake/vmb"
        }
      }
    },
    {
      "name": "linux64",
      "inherits": "linux64-template",
      "displayName": "Linux 64 Release Config",
      "description": "Linux 64 Release Config",
      "cacheVariables": {
        "Vmb_DIR": {
          "type": "PATH",
          "value": "/home/User/Desktop/VimbaX_2023-1/api/lib/cmake/vmb"
        }
      }
    },
    {
      "name": "linux64-debug",
      "inherits": ["linux64-debug-template", "linux64"],
      "displayName": "Linux 64 Debug Config",
      "description": "Linux 64 Debug Config"
    },
    {
      "name": "arm64",
      "inherits": "arm64-template",
      "displayName": "Linux ARM64 Release Config",
      "description": "Linux ARM64 Release Config",
      "cacheVariables": {
      }
    },
    {
      "name": "arm64-debug",
      "inherits": ["arm64-debug-template", "arm64"],
      "displayName": "Linux ARM64 Debug Config",
      "description": "Linux ARM64 Debug Config"
    }
  ],
  
  "buildPresets": [
    {
      "name": "build-template",
      "hidden": true,
      "jobs": 8,
      "targets": ["gstvmbsrc"]
    },
    {
      "name": "win64",
      "inherits": "build-template",
      "configurePreset": "win64",
      "configuration": "Release"
    },
    {
      "name": "win64-debug",
      "inherits": "win64",
      "configuration": "Debug"      
    }
  ]
}

############################################

- Distribution/Version: Ubuntu 20.04
- CMake version: cmake version 3.16.3

**Comment by NiklasKroeger-AlliedVision** [comment]
I believe the issue is that your CMake version does not yet support the CMakeUserPreset.json file. This was apparently introduced in CMake 3.19 if I am reading the release notes correctly. https://cmake.org/cmake/help/latest/release/3.19.html and https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html

This would mean that CMakeUserPresets.json is probably completely ignored by your CMake execution. You could try and define the `Vmb_DIR` cache variable on the command you execute. So perhaps try the following commands.

```
$ cd </path/to/your/repository/clone>
$ cmake -S . -B build -DVmb_DIR=/home/User/Desktop/VimbaX_2023-1/api/lib/cmake/vmb
$ cmake --build build
```

The second command should create a directory named `build` in your cloned repository and perform the cmake configuration step. The `-D...` part defines the `Vmb_DIR` CMake Cache Variable with the required path.

With the third command a build should be executed.

Alternatively you could try upgrading your CMake version to one that supports the presets that this repository provides.

**Comment by mrhen2324** [comment]
You're right. This solved my problem! Thank you.
I used the three commands you gave me. The build directory could be created and executed.
Libgstvmbsrc has been recognized by Gstreamer and can be used.
