### ISSUE TITLE
Camera sometimes thrown into a bad state requiring power cycle

### ISSUE THREAD

**Issue by cdelguercio** [alliedvision/gst-vmbsrc#4]
My gstreamer pipeline fails with:

```
terminate called after throwing an instance of 'GenICam_3_2_AVT::AccessException'
```

**Comment by Teresa-AlliedVision** [comment]
Could you give some more information on when and how the error occurs? Additionally, your camera model, firmware version, VimbaX version, gst-vbsrc version and OS.

**Comment by cdelguercio** [comment]
Model: G1-240c
Firmware: 00.13.00 & 00.13.01
OS: Ubuntu 23.10
gst-vmbsrc: HEAD
VimbaX: 2023-4

The camera refuses to connect to my gstreamer pipeline or be updated with the firmware updater unless I power cycle the camera.

Running ./ListCameras_VmbC yields
```
/// Permitted Access Modes : Read access
```

I could reset the Access Mode by running a vmbpy script that initializes the camera, but still couldn't connect to my gstreamer pipeline or the firmware updater without power cycling.

**Comment by Teresa-AlliedVision** [comment]
That does not sound like it is connected to the Gstreamer plugin, more to the camera being openened in another process. Please make sure you properly close the camera in any of your programs and close all programs that can accesses the camera, before starting your pipeline. Including the firmware updater and any type of viewer.
I would recommend sending a support request through our website or the distributor you bought the camera from, if closing all programs does not help:
https://www.alliedvision.com/en/about-us/contact-us/technical-support-repair-/-rma/
