### ISSUE TITLE
ERROR: gst_parse_error: no element "vmbsrc"

### ISSUE THREAD

**Issue by AhmedL99** [alliedvision/gst-vmbsrc#5]
###  **System infos:**

- **OS:** Ubuntu 20.04
- **GStreamer version:** 1.16.3
- **VimbaX version**: 2023-4
- **gst-vmbsrc version:** 1.0.0

### **Bug description:** 
After the installation of gst-vmbsrc and successfully running this command in CLI 
```
gst-launch-1.0 vmbsrc camera=<cam_ID> num-buffers=1 ! pngenc ! filesink location=out.png
``` 
I attempted to execute the same command using Python and the gi library, but encountered this error: 
```
  File "fpd_metrics_checker.py", line 34, in <module>
    pipeline = Gst.parse_launch(pipeline_str)
gi.repository.GLib.Error: gst_parse_error: no element "vmbsrc" (1)
```
Gst global variables `GST_PLUGIN_SYSTEM_PATH` & `GST_PLUGIN_PATH` are set to the appropriate plugin folder and we had even used the `Gst.Registry.scan_path()` option.

The goal is to launch the GStreamer command and extract certain metrics ( no need for `VmbPy`) 

Looking forward to hearing from you,
Ahmed

**Comment by Teresa-AlliedVision** [comment]
Hello Ahmed,
what camera model are you using? Specifically the interface.
Next:
Do you have the python plugin loader installed? Check with `gst-inspect-1.0 python`.
If not, install with `sudo apt install gstreamer1.0-python3-plugin-loader`.
What folder is the plugin in, is it specifically plugins/python?

**Comment by AhmedL99** [comment]
The problem was solved by installing the plugin loader, thanks a lot!

**Comment by Teresa-AlliedVision** [comment]
Great, thank you for the feedback. The missing plugin loader is a general issue in the current gstreamer python module version it seems.
